### ISSUE TITLE
Make Donation Page Responsive

### ISSUE THREAD

**Issue by mdnazisharman2803** [ShrutiMishra-2002/hacktoberfest22_transopedia#5] opened 2022-10-01 08:42 UTC
- Visit the link to check the details of the page to be worked on https://shrutimishra-2002.github.io/Transopedia-website/storeanddonate/donation.html

**Comment by DugarRishab** [comment] 2022-10-01 09:14
Hey, @mdnazisharman2803 as I am working on #7 I would also like to work o this issue. I believe that both issues can be solved together.

**Comment by aksha123-git** [comment] 2022-10-01 09:24
I would to contribute on this issue @mdnazisharman2803

**Comment by jyotika6221** [comment] 2022-10-08 06:56
If the issue isnt solved yet, please assign it to me.

**Comment by ShrutiMishra-2002** [comment] 2022-10-08 09:30
@jyotika6221 done goahead

**Closed** 2022-10-09 13:21 UTC
Labels: good first issue, hacktoberfest, Beginner

**Comment by jyotika6221** [comment] 2022-10-09 13:33
You closed the repo, what do i do now?
